### ISSUE TITLE
Installation instruction please

### ISSUE THREAD

**Issue by A1-TheDarkKnight** [PavelBlend/Blender-SPlisHSPlasH#1]
can you help me please with some installation instructions .
Best regards

**Comment by PavelBlend** [comment]
This addon is not completed yet. He will not work.

**Comment by A1-TheDarkKnight** [comment]
Thank you for your quick reply, and big thanks for your hard work.
can we expect it to be completed in the near future ?
keep up the good work.
Best regards

**Comment by PavelBlend** [comment]
At the moment I am not developing this addon.
I also contacted the developers of SpliSHSPlasH and they said that in the future they themselves will do integration with the blender.

**Comment by A1-TheDarkKnight** [comment]
Thanks a lot for your work , and i hope you all the best.
Best regards
